version: "3.7"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=tlc
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  back:
    build: ./api/
    ports: 
      - "8080:8080"
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  front:
    build: ./front/
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./api/server-confs:/server-confs:ro
      - ./certificates:/etc/letsencrypt:rw
    environment:
      - SERVER_NAME=dshs.istic.univ-rennes1.fr
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - USE_CLIENT_CACHE=yes
  myadmin:
    image : phpmyadmin
    ports:
      - "8082:80"